export const SENDING_MESSAGE_REQUEST = "SENDING_MESSAGE_REQUEST"
export const SENDING_MESSAGE_SUCCESS = "SENDING_MESSAGE_SUCCESS"
export const SENDING_MESSAGE_FAIL = "SENDING_MESSAGE_FAIL"

export const GETTING_MESSAGE_REQUEST = "GETTING_MESSAGE_REQUEST"
export const GETTING_MESSAGE_SUCCESS = "GETTING_MESSAGE_SUCCESS"
export const GETTING_MESSAGE_FAIL = "GETTING_MESSAGE_FAIL"